package daniel.bertoldi.geographyquiz

import android.util.Log
import androidx.lifecycle.ViewModel
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import retrofit2.Call
import retrofit2.Callback
import retrofit2.Response
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.GET
import retrofit2.http.Path
import javax.inject.Inject

sealed class ScreenState {
    data object Loading : ScreenState()
    data object Success : ScreenState()
    data object Failed : ScreenState()
    data object SelectContinent : ScreenState()

    data class StartGame(val chosenContinent: Continent) : ScreenState()
}

enum class Continent {
    NORTH_AMERICA,
    SOUTH_AMERICA,
    EUROPE,
    AFRICA,
    ASIA,
    OCEANIA
}

@HiltViewModel
class MainActivityViewModel @Inject constructor() : ViewModel() {
    private val _countries = MutableStateFlow<List<String>>(emptyList())
    val countries: StateFlow<List<String>> = _countries.asStateFlow()
    private val _state = MutableStateFlow<ScreenState>(ScreenState.Loading)
    val state: StateFlow<ScreenState> = _state.asStateFlow()

    fun init() {
        val moshi = Moshi.Builder()
            .addLast(KotlinJsonAdapterFactory())
            .build()
        val retrofit = Retrofit.Builder()
            .baseUrl("https://flagcdn.com")
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .build()
            .create(APIInterface::class.java)

        retrofit.getCountries().enqueue(
            object : Callback<Countries2> {
                override fun onResponse(p0: Call<Countries2>, p1: Response<Countries2>) {
                    if (p1.isSuccessful) {
                        _state.value = ScreenState.Success
                        _countries.value = p1.body()?.let {
                            listOf(
                                it.AD,
                                it.AE,
                                it.AF,
                                it.AG,
                                it.AI,
                                it.AL,
                                it.AM,
                                it.AO,
                                it.AQ,
                                it.AR,
                                it.AS,
                                it.AT,
                                it.AU,
                                it.AW,
                                it.AX,
                                it.AZ,
                                it.BA,
                                it.BB,
                                it.BD,
                                it.BE,
                                it.BF,
                                it.BG,
                                it.BH,
                                it.BI,
                                it.BJ,
                                it.BL,
                                it.BM,
                                it.BN,
                                it.BO,
                                it.BQ,
                                it.BR,
                                it.BS,
                                it.BT,
                                it.BV,
                                it.BW,
                                it.BY,
                                it.BZ,
                                it.CA,
                                it.CC,
                                it.CD,
                                it.CF,
                                it.CG,
                                it.CH,
                                it.CI,
                                it.CK,
                                it.CL,
                                it.CM,
                                it.CN,
                                it.CO,
                                it.CR,
                                it.CU,
                                it.CV,
                                it.CW,
                                it.CX,
                                it.CY,
                                it.CZ,
                                it.DE,
                                it.DJ,
                                it.DK,
                                it.DM,
                                it.DO,
                                it.DZ,
                                it.EC,
                                it.EE,
                                it.EG,
                                it.EH,
                                it.ER,
                                it.ES,
                                it.ET,
                                it.EU,
                                it.FI,
                                it.FJ,
                                it.FK,
                                it.FM,
                                it.FO,
                                it.FR,
                                it.GA,
                                it.GB,
                                it.GD,
                                it.GE,
                                it.GF,
                                it.GG,
                                it.GH,
                                it.GI,
                                it.GL,
                                it.GM,
                                it.GN,
                                it.GP,
                                it.GQ,
                                it.GR,
                                it.GS,
                                it.GT,
                                it.GU,
                                it.GW,
                                it.GY,
                                it.HK,
                                it.HM,
                                it.HN,
                                it.HR,
                                it.HT,
                                it.HU,
                                it.ID,
                                it.IE,
                                it.IL,
                                it.IM,
                                it.IN,
                                it.IO,
                                it.IQ,
                                it.IR,
                                it.IS,
                                it.IT,
                                it.JE,
                                it.JM,
                                it.JO,
                                it.JP,
                                it.KE,
                                it.KG,
                                it.KH,
                                it.KI,
                                it.KM,
                                it.KN,
                                it.KP,
                                it.KR,
                                it.KW,
                                it.KY,
                                it.KZ,
                                it.LA,
                                it.LB,
                                it.LC,
                                it.LI,
                                it.LK,
                                it.LR,
                                it.LS,
                                it.LT,
                                it.LU,
                                it.LV,
                                it.LY,
                                it.MA,
                                it.MC,
                                it.MD,
                                it.ME,
                                it.MF,
                                it.MG,
                                it.MH,
                                it.MK,
                                it.ML,
                                it.MM,
                                it.MN,
                                it.MO,
                                it.MP,
                                it.MQ,
                                it.MR,
                                it.MS,
                                it.MT,
                                it.MU,
                                it.MV,
                                it.MW,
                                it.MX,
                                it.MY,
                                it.MZ,
                                it.NA,
                                it.NC,
                                it.NE,
                                it.NF,
                                it.NG,
                                it.NI,
                                it.NL,
                                it.NO,
                                it.NP,
                                it.NR,
                                it.NU,
                                it.NZ,
                                it.OM,
                                it.PA,
                                it.PE,
                                it.PF,
                                it.PG,
                                it.PH,
                                it.PK,
                                it.PL,
                                it.PM,
                                it.PN,
                                it.PR,
                                it.PS,
                                it.PT,
                                it.PW,
                                it.PY,
                                it.QA,
                                it.RE,
                                it.RO,
                                it.RS,
                                it.RU,
                                it.RW,
                                it.SA,
                                it.SB,
                                it.SC,
                                it.SD,
                                it.SE,
                                it.SG,
                                it.SH,
                                it.SI,
                                it.SJ,
                                it.SK,
                                it.SL,
                                it.SM,
                                it.SN,
                                it.SO,
                                it.SR,
                                it.SS,
                                it.ST,
                                it.SV,
                                it.SX,
                                it.SY,
                                it.SZ,
                                it.TC,
                                it.TD,
                                it.TF,
                                it.TG,
                                it.TH,
                                it.TJ,
                                it.TK,
                                it.TL,
                                it.TM,
                                it.TN,
                                it.TO,
                                it.TR,
                                it.TT,
                                it.TV,
                                it.TW,
                                it.TZ,
                                it.UA,
                                it.UG,
                                it.UM,
                                it.UN,
                                it.US,
                                it.UY,
                                it.UZ,
                                it.VA,
                                it.VC,
                                it.VE,
                                it.VG,
                                it.VI,
                                it.VN,
                                it.VU,
                                it.WF,
                                it.WS,
                                it.XK,
                                it.YE,
                                it.YT,
                                it.ZA,
                                it.ZM,
                                it.ZW,
                            )
                        } ?: emptyList()
                    }
                }

                override fun onFailure(p0: Call<Countries2>, p1: Throwable) {
                    /* do nothing */
                    _state.value = ScreenState.Failed
                    Log.d("WHAT", "yeah it bugged out")
                    Log.d("WHAT", p1.stackTraceToString())
                }
            }
        )
    }

    interface APIInterface {
        @GET("{language}/codes.json")
        fun getCountries(@Path("language") language: String = "pt"): Call<Countries2>
    }

    fun startGame() {
        _state.value = ScreenState.SelectContinent
    }

    fun startActualGame(continent: Continent) {
        _state.value = ScreenState.StartGame(continent)
    }
}

@JsonClass(generateAdapter = true)
data class Countries2(
    @Json(name = "ad") val AD: String,
    @Json(name = "ae") val AE: String,
    @Json(name = "af") val AF: String,
    @Json(name = "ag") val AG: String,
    @Json(name = "ai") val AI: String,
    @Json(name = "al") val AL: String,
    @Json(name = "am") val AM: String,
    @Json(name = "ao") val AO: String,
    @Json(name = "aq") val AQ: String,
    @Json(name = "ar") val AR: String,
    @Json(name = "as") val AS: String,
    @Json(name = "at") val AT: String,
    @Json(name = "au") val AU: String,
    @Json(name = "aw") val AW: String,
    @Json(name = "ax") val AX: String,
    @Json(name = "az") val AZ: String,
    @Json(name = "ba") val BA: String,
    @Json(name = "bb") val BB: String,
    @Json(name = "bd") val BD: String,
    @Json(name = "be") val BE: String,
    @Json(name = "bf") val BF: String,
    @Json(name = "bg") val BG: String,
    @Json(name = "bh") val BH: String,
    @Json(name = "bi") val BI: String,
    @Json(name = "bj") val BJ: String,
    @Json(name = "bl") val BL: String,
    @Json(name = "bm") val BM: String,
    @Json(name = "bn") val BN: String,
    @Json(name = "bo") val BO: String,
    @Json(name = "bq") val BQ: String,
    @Json(name = "br") val BR: String,
    @Json(name = "bs") val BS: String,
    @Json(name = "bt") val BT: String,
    @Json(name = "bv") val BV: String,
    @Json(name = "bw") val BW: String,
    @Json(name = "by") val BY: String,
    @Json(name = "bz") val BZ: String,
    @Json(name = "ca") val CA: String,
    @Json(name = "cc") val CC: String,
    @Json(name = "cd") val CD: String,
    @Json(name = "cf") val CF: String,
    @Json(name = "cg") val CG: String,
    @Json(name = "ch") val CH: String,
    @Json(name = "ci") val CI: String,
    @Json(name = "ck") val CK: String,
    @Json(name = "cl") val CL: String,
    @Json(name = "cm") val CM: String,
    @Json(name = "cn") val CN: String,
    @Json(name = "co") val CO: String,
    @Json(name = "cr") val CR: String,
    @Json(name = "cu") val CU: String,
    @Json(name = "cv") val CV: String,
    @Json(name = "cw") val CW: String,
    @Json(name = "cx") val CX: String,
    @Json(name = "cy") val CY: String,
    @Json(name = "cz") val CZ: String,
    @Json(name = "de") val DE: String,
    @Json(name = "dj") val DJ: String,
    @Json(name = "dk") val DK: String,
    @Json(name = "dm") val DM: String,
    @Json(name = "do") val DO: String,
    @Json(name = "dz") val DZ: String,
    @Json(name = "ec") val EC: String,
    @Json(name = "ee") val EE: String,
    @Json(name = "eg") val EG: String,
    @Json(name = "eh") val EH: String,
    @Json(name = "er") val ER: String,
    @Json(name = "es") val ES: String,
    @Json(name = "et") val ET: String,
    @Json(name = "eu") val EU: String,
    @Json(name = "fi") val FI: String,
    @Json(name = "fj") val FJ: String,
    @Json(name = "fk") val FK: String,
    @Json(name = "fm") val FM: String,
    @Json(name = "fo") val FO: String,
    @Json(name = "fr") val FR: String,
    @Json(name = "ga") val GA: String,
    @Json(name = "gb") val GB: String,
    @Json(name = "gd") val GD: String,
    @Json(name = "ge") val GE: String,
    @Json(name = "gf") val GF: String,
    @Json(name = "gg") val GG: String,
    @Json(name = "gh") val GH: String,
    @Json(name = "gi") val GI: String,
    @Json(name = "gl") val GL: String,
    @Json(name = "gm") val GM: String,
    @Json(name = "gn") val GN: String,
    @Json(name = "gp") val GP: String,
    @Json(name = "gq") val GQ: String,
    @Json(name = "gr") val GR: String,
    @Json(name = "gs") val GS: String,
    @Json(name = "gt") val GT: String,
    @Json(name = "gu") val GU: String,
    @Json(name = "gw") val GW: String,
    @Json(name = "gy") val GY: String,
    @Json(name = "hk") val HK: String,
    @Json(name = "hm") val HM: String,
    @Json(name = "hn") val HN: String,
    @Json(name = "hr") val HR: String,
    @Json(name = "ht") val HT: String,
    @Json(name = "hu") val HU: String,
    @Json(name = "id") val ID: String,
    @Json(name = "ie") val IE: String,
    @Json(name = "il") val IL: String,
    @Json(name = "im") val IM: String,
    @Json(name = "in") val IN: String,
    @Json(name = "io") val IO: String,
    @Json(name = "iq") val IQ: String,
    @Json(name = "ir") val IR: String,
    @Json(name = "is") val IS: String,
    @Json(name = "it") val IT: String,
    @Json(name = "je") val JE: String,
    @Json(name = "jm") val JM: String,
    @Json(name = "jo") val JO: String,
    @Json(name = "jp") val JP: String,
    @Json(name = "ke") val KE: String,
    @Json(name = "kg") val KG: String,
    @Json(name = "kh") val KH: String,
    @Json(name = "ki") val KI: String,
    @Json(name = "km") val KM: String,
    @Json(name = "kn") val KN: String,
    @Json(name = "kp") val KP: String,
    @Json(name = "kr") val KR: String,
    @Json(name = "kw") val KW: String,
    @Json(name = "ky") val KY: String,
    @Json(name = "kz") val KZ: String,
    @Json(name = "la") val LA: String,
    @Json(name = "lb") val LB: String,
    @Json(name = "lc") val LC: String,
    @Json(name = "li") val LI: String,
    @Json(name = "lk") val LK: String,
    @Json(name = "lr") val LR: String,
    @Json(name = "ls") val LS: String,
    @Json(name = "lt") val LT: String,
    @Json(name = "lu") val LU: String,
    @Json(name = "lv") val LV: String,
    @Json(name = "ly") val LY: String,
    @Json(name = "ma") val MA: String,
    @Json(name = "mc") val MC: String,
    @Json(name = "md") val MD: String,
    @Json(name = "me") val ME: String,
    @Json(name = "mf") val MF: String,
    @Json(name = "mg") val MG: String,
    @Json(name = "mh") val MH: String,
    @Json(name = "mk") val MK: String,
    @Json(name = "ml") val ML: String,
    @Json(name = "mm") val MM: String,
    @Json(name = "mn") val MN: String,
    @Json(name = "mo") val MO: String,
    @Json(name = "mp") val MP: String,
    @Json(name = "mq") val MQ: String,
    @Json(name = "mr") val MR: String,
    @Json(name = "ms") val MS: String,
    @Json(name = "mt") val MT: String,
    @Json(name = "mu") val MU: String,
    @Json(name = "mv") val MV: String,
    @Json(name = "mw") val MW: String,
    @Json(name = "mx") val MX: String,
    @Json(name = "my") val MY: String,
    @Json(name = "mz") val MZ: String,
    @Json(name = "na") val NA: String,
    @Json(name = "nc") val NC: String,
    @Json(name = "ne") val NE: String,
    @Json(name = "nf") val NF: String,
    @Json(name = "ng") val NG: String,
    @Json(name = "ni") val NI: String,
    @Json(name = "nl") val NL: String,
    @Json(name = "no") val NO: String,
    @Json(name = "np") val NP: String,
    @Json(name = "nr") val NR: String,
    @Json(name = "nu") val NU: String,
    @Json(name = "nz") val NZ: String,
    @Json(name = "om") val OM: String,
    @Json(name = "pa") val PA: String,
    @Json(name = "pe") val PE: String,
    @Json(name = "pf") val PF: String,
    @Json(name = "pg") val PG: String,
    @Json(name = "ph") val PH: String,
    @Json(name = "pk") val PK: String,
    @Json(name = "pl") val PL: String,
    @Json(name = "pm") val PM: String,
    @Json(name = "pn") val PN: String,
    @Json(name = "pr") val PR: String,
    @Json(name = "ps") val PS: String,
    @Json(name = "pt") val PT: String,
    @Json(name = "pw") val PW: String,
    @Json(name = "py") val PY: String,
    @Json(name = "qa") val QA: String,
    @Json(name = "re") val RE: String,
    @Json(name = "ro") val RO: String,
    @Json(name = "rs") val RS: String,
    @Json(name = "ru") val RU: String,
    @Json(name = "rw") val RW: String,
    @Json(name = "sa") val SA: String,
    @Json(name = "sb") val SB: String,
    @Json(name = "sc") val SC: String,
    @Json(name = "sd") val SD: String,
    @Json(name = "se") val SE: String,
    @Json(name = "sg") val SG: String,
    @Json(name = "sh") val SH: String,
    @Json(name = "si") val SI: String,
    @Json(name = "sj") val SJ: String,
    @Json(name = "sk") val SK: String,
    @Json(name = "sl") val SL: String,
    @Json(name = "sm") val SM: String,
    @Json(name = "sn") val SN: String,
    @Json(name = "so") val SO: String,
    @Json(name = "sr") val SR: String,
    @Json(name = "ss") val SS: String,
    @Json(name = "st") val ST: String,
    @Json(name = "sv") val SV: String,
    @Json(name = "sx") val SX: String,
    @Json(name = "sy") val SY: String,
    @Json(name = "sz") val SZ: String,
    @Json(name = "tc") val TC: String,
    @Json(name = "td") val TD: String,
    @Json(name = "tf") val TF: String,
    @Json(name = "tg") val TG: String,
    @Json(name = "th") val TH: String,
    @Json(name = "tj") val TJ: String,
    @Json(name = "tk") val TK: String,
    @Json(name = "tl") val TL: String,
    @Json(name = "tm") val TM: String,
    @Json(name = "tn") val TN: String,
    @Json(name = "to") val TO: String,
    @Json(name = "tr") val TR: String,
    @Json(name = "tt") val TT: String,
    @Json(name = "tv") val TV: String,
    @Json(name = "tw") val TW: String,
    @Json(name = "tz") val TZ: String,
    @Json(name = "ua") val UA: String,
    @Json(name = "ug") val UG: String,
    @Json(name = "um") val UM: String,
    @Json(name = "un") val UN: String,
    @Json(name = "us") val US: String,
    @Json(name = "uy") val UY: String,
    @Json(name = "uz") val UZ: String,
    @Json(name = "va") val VA: String,
    @Json(name = "vc") val VC: String,
    @Json(name = "ve") val VE: String,
    @Json(name = "vg") val VG: String,
    @Json(name = "vi") val VI: String,
    @Json(name = "vn") val VN: String,
    @Json(name = "vu") val VU: String,
    @Json(name = "wf") val WF: String,
    @Json(name = "ws") val WS: String,
    @Json(name = "xk") val XK: String,
    @Json(name = "ye") val YE: String,
    @Json(name = "yt") val YT: String,
    @Json(name = "za") val ZA: String,
    @Json(name = "zm") val ZM: String,
    @Json(name = "zw") val ZW: String,
)